[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm install --include=dev']

[phases.build]
cmds = [
  'npm run build:shared',
  'npm run build:server'
]

[start]
cmd = 'cd server && npm start'
