name = "fssphone-server"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "e4dbf5d535fc83344f8f12af566d9992"

[observability]
[observability.logs]
enabled = true
invocation_logs = true


[vars]
VATSIM_AUTH_URL = "https://auth.vatsim.net"
CLIENT_URL = "https://client.virtualfssphone.cc"
REQUIRE_VATSIM_CONNECTION = "false"

# Secrets (set via `wrangler secret put`):
# VATSIM_CLIENT_ID
# VATSIM_CLIENT_SECRET
# VATSIM_REDIRECT_URI
# JWT_SECRET
#67

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "LobbyDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LobbyDO"]
